# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-29 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Location', models.CharField(max_length=30)),
                ('Mobile', models.CharField(default=0, max_length=10, unique=True)),
            ],
        ),
    ]
